### ISSUE TITLE
PCD Assembly service files?

### ISSUE THREAD

**Issue by Tsaukpaetra** [serisman/HIDman-mini#1]
I'm a bit inexperienced with ordering PCBs and I see that you have the gerber file for the PCB itself, but I was wondering if you had the other files for ordering assembly from the likes of PCBWay or JLPCB? Their options are a bit daunting.

Ideally if there was a way to one-click configure the project that would be cool, but if I could otherwise get their required files I could possibly bumble about and get it done. I can solder but surface-mount is a bit beyond my abilities. 😇

**Comment by serisman** [comment]
Sorry, I have no experience with ordering assembled PCBs.  These PCBs weren't designed with automated assembly in mind.  They have components on both sides of the board, which doesn't work well with typical cheap assembly services like JLCPCB and PCBWay offer.  I designed these for my own limited use, and hand soldered them.  Not too bad with some SMD experience, but probably not what you want to learn on.

**Comment by GrantMTG** [comment]
There's a guy on Tindie that sells CH559 breakout boards with the USB jacks and a few other parts mounted. You could cut some cables and solder them to those boards probably.
