### ISSUE TITLE
Firmware?

### ISSUE THREAD

**Issue by dukeyusupov** [serisman/HIDman-mini#3]
Is the firmware from HIDman suitable? Nothing works for me with it...
Rasteri write:
"I didn't really have anything to do with the mini board, but the firmware in the github definitely won't work.
I've tried to compile the latest firmware for mini boards but it may or may not work"

**Comment by serisman** [comment]
It certainly worked with the HIDman firmware a while ago, but that firmware has seen a lot of changes recently and I haven't checked in a year or so.

You might need to use an older version of the firmware or wait until compatibility can be re-checked/fixed.

My fork of the HIDman repo (https://github.com/serisman/HIDman) hasn't been updated in a while, and should still work.

**Comment by serisman** [comment]
I just tested with the following version of the HIDman firmware that rasteri custom compiled and it seems to be working fine on one of my HIDman-mini boards:
[hidmanmini.zip](https://github.com/user-attachments/files/17166206/hidmanmini.zip)

Apparently rasteri added an external crystal to his AXP board that has to be disabled in order for the mini to operate.  There are options in the Makefile to switch back to the internal oscillator.

**Comment by serisman** [comment]
I just added pre-compiled binaries for v1.1.3 for both HIDman-mini and HIDman-micro available here:
https://github.com/serisman/HIDman-mini/releases/tag/v1.1.3
